### PR TITLE
Add option to separate coordinate calculation/plot

### PR DESCRIPTION
**Pull request by HaoLi111**
see this demo (from one of the example file):

```

prim_rules <- data.frame(inp = c("0", "1"),
                         out = c("1[+0]-0", "11"), stringsAsFactors = FALSE)
primitive_plant <- Lsys(init = "0", rules = prim_rules, n = 7)
draw_prim <- data.frame(symbol = c("0", "1", "+", "-", "[", "]"),
                        action = c("F", "F", "+", "-", "[", "]"), stringsAsFactors = FALSE)
coordDf =recLsys(string = primitive_plant, stepSize = 1, ang = 45, st = c(50, 5, 90),
         drules = draw_prim, which = 7)
#grid.text("Primitive Tree (n = 6)", 0.5, 0.75)


library(ggplot2)

#alpha = numeric(nrow(coordDf))
alpha= rep(1,(nrow(coordDf)))#color all paths with no transparency
index_rev = which(as.vector.factor(coordDf$pType)=="r")

index_beforeRev = index_rev-1
for(i in index_beforeRev) alpha[i] = .1

coordDf$alpha = alpha

ggplot(data =coordDf,aes(x = x,y = y,
                         alpha = alpha)) + geom_path()

ggLsys(primitive_plant, stepSize = 1, ang = 45, st = c(50, 5, 90),
        drules = draw_prim, which = 7)


```

### CODE REVIEW

**Comment by bryanhanson** [comment]
Hao, I'm traveling all day today so I will review tomorrow (Wednesday).  Bryan

**Comment by bryanhanson** [comment]
OK, I've had a chance to review this.  I like it and I see where you are going with things.  Thank you. Some comments:

- As you may have noticed, I built and checked my local version against R 3.6 to make sure everything works correctly.  I then pushed it along with a currently identical `devel` branch to Github.  Can you please submit your pull request to the `devel` branch and let's work there, so as to not bother the functioning `master` branch.
- Can you add appropriate roxygen2 tags and documentation to the functions you wrote?
- With your changes to `drawLsys`, the return value needs to be documented.
- Please use `TRUE` and `FALSE` instead of `T` and `F`.
- Also, it looks to me like in `drawLsys` at the point when `isTRUE(record)`, you could call`recLys`. Doing so removes a big section of code and that makes maintenance much easier.
- For now, I don't want to abandon the interactive plotting option, but perhaps in the future.  One reason is that `ggplot2` can be very slow with large data sets, so we should benchmark.
- We also have to be careful to watch for `ggplot2` changes, that API has changed a lot in the past.  A new version is due in a month.

**Comment by HaoLi111** [comment]
Thanks


- no problem calling recLys and other options
- though roxygen2 did not work properly on my laptop. I 'll try to fix this and try to write the docu with my awkward English lol
- the main point of recLsys is to get the coordinates and  ggplot is just one way of checking the validity
- maybe there are even better plotting options, like calling gl for interactive plotting, or use pixel marks that directly write a tiff image via tiff package. I record the coordinates s.t. scaling and transformation can get easy

**Comment by HaoLi111** [comment]
@bryanhanson 
It reminded me about one thing: during the research of fractals, sooner or later (or, very soon) will we need a fast and also powerful graphical engine to be connected with Lsys, for which ggplot, grid and lattice are not suitable (because they use standard graphics device). Things like trelliscope and plotly are too  "data-scientistical" and may be over complicated. OpenGL may be one choice but the implementation of GL in R (see package 'rgl', 'plot3Drgl' and plot2Drgl() function) are not as convenient for saving plot objects. I have tried to load very large dataset to plot3Drgl (about 500MB) before and it occasionally breaks (it would be more difficult to fix these wrappers).

I have written another package to directly render TIFF from x and coordinates (in R, vectorized for speed) for large datasets (because large arrays crashes grdevices and use too much memory). But it only handles 2d map, contours and scatters.

So I guess with current solutions (grid and ggplot) is just to make a small prototype of graphics. In the future, working on rgl instead of plot3Drgl may be one transitional solution?


Do you have other recommendations on graphic engines?

**Comment by HaoLi111** [comment]
Screenshots as ggplot is loaded
https://github.com/tidyverse/ggplot2/issues/3249
and my primitive solution
https://github.com/HaoLi111/GigaDataPlotRenderer

**Comment by bryanhanson** [comment]
There is a brand new package using GPU's: https://cran.r-project.org/web/packages/gpuR/index.html I only looked at it briefly but it looks interesting.

**Comment by HaoLi111** [comment]
Great. Thanks for pointing that out. As for performance problems (creating multiple files for Lsys and make animations, for hundreds of plots created, this may be a temporary solution [https://github.com/HaoLi111/distribute-R-tasks-with-pure-R](https://github.com/HaoLi111/distribute-R-tasks-with-pure-R) )
Sorry I have some other codes to do, will get this fixed by the end of June.

**Pull request closed without merging**
